# application-aws.properties

spring.datasource.url=jdbc:mysql://${RDS_HOSTNAME:${AWS_RDS_HOST}}:${RDS_PORT:3306}/${RDS_DB_NAME:expensetracker}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${RDS_USERNAME:admin}
spring.datasource.password=${RDS_PASSWORD:change-me}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.thymeleaf.cache=true

server.port=5000

