#spring.datasource.url=${LOCAL_DB_URL:jdbc:mysql://localhost:3306/expensetracker?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false}

spring.datasource.url=${LOCAL_DB_URL:jdbc:mysql://localhost:3306/expensetracker?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${LOCAL_DB_USER:root}
spring.datasource.password=${LOCAL_DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
